### ISSUE TITLE
Ambiguous Description

### ISSUE THREAD

**Issue by jai-yadav** [iiFir3z/debugify#12]
In ReadMe, it says that _"PLEASE NOTE THIS ONLY WORKS ON 13.X DEVICES I have only tested this on the 6,6s,7,7P,8,8P,X"_

But for iPhone 6, iOS 13 was not released, How did you test it?

Not working for me on iPhone 6 with iOS 12.4.7.

**Comment by iiFir3z** [comment]
Must have been a typo fixing currently.
