### ISSUE TITLE
My phone is becoming increasingly verbose after failed install

### ISSUE THREAD

**Issue by Bango88** [iiFir3z/debugify#14]
The script failed to install, so I ldrestarted and now this is happening:![image](https://user-images.githubusercontent.com/47485594/84815530-2a46b200-afe1-11ea-8b1a-70f722368c67.png)![image](https://user-images.githubusercontent.com/47485594/84815548-2f0b6600-afe1-11ea-996b-f849534f0f08.png)![Uploading 84815562...]()

**Comment by jai-yadav** [comment]
+1, happened with me also, had to reset my device, thank god I was doing it on my spare device (6s+)

**Comment by iiFir3z** [comment]
When you install Debugify your iPhone or iPad is considered a Internal build and will show verbose there may be a internal option to turn it off but as far as I know that is a product of the internal bundles.

Closing as this isn't an issue however if you can provide logs with the script failing that would be amazing!

**Comment by Bango88** [comment]
@iiFir3z, the script just crashed, I then ran it again but choose to remove it, the verbose wording is still there. As for logs, where are they located
