### ISSUE TITLE
http://35.230.4.142/debugify/privateframeworks.tar.xz Not working

### ISSUE THREAD

**Issue by bipbapbam** [iiFir3z/debugify#16]
![Capture](https://user-images.githubusercontent.com/15622105/87700655-aa894000-c764-11ea-98a6-ca044b3cf2d0.PNG)

Unable to install debugify via debugify.sh or installeronly.sh. When trying to connect to http://35.230.4.142/debugify/privateframeworks.tar.xz, the operation times out. 

iPhone X running iOS 13.5

**Comment by iiFir3z** [comment]
Try running the new updated version again.

**Comment by bipbapbam** [comment]
![image](https://user-images.githubusercontent.com/15622105/87704475-7284fb80-c76a-11ea-8b2f-631ab5ad791b.png)
This is what I get when trying the updated debugify.sh
It still doesn't times out when trying with installeronly.sh
![image](https://user-images.githubusercontent.com/15622105/87704582-a06a4000-c76a-11ea-94f8-97760e9938d2.png)

**Comment by bipbapbam** [comment]
![image](https://user-images.githubusercontent.com/15622105/87706339-58005180-c76d-11ea-81a3-ac6b4fc8b036.png)
I get this when trying to run it a via "sh debugify.sh"

**Comment by iiFir3z** [comment]
Ill take a look at the issue.
