### ISSUE TITLE
Impossible chose band

### ISSUE THREAD

**Issue by BolsaFamillia** [iiFir3z/debugify#17]
I'm not able to choose the LTE bands, when I open the "band" tab, it doesn't show anything, everything is empty. What do I do to correct this problem? Iphone 6s plus ios 13.5 with checkra1n 0.10.2

**Comment by iiFir3z** [comment]
The build used is for the 7 and up for most things so band choosing won’t
work I believe.

**Comment by BolsaFamillia** [comment]
Really? Don't have any way to make it work? Or some other method or tweak that you follow? I really need to choose the lte band.

**Comment by iiFir3z** [comment]
Until I find another build or implement more versions this sadly is impossible to do. I'm not quite sure about the tweak side of things but Debugify doesn't currently have the support for that device entirely yet.
