### ISSUE TITLE
not working on ios 13.6 / iphone 8

### ISSUE THREAD

**Issue by jkrosado** [iiFir3z/debugify#18]
i went through all the steps correctly, this is what it said
```Credits: @B355P
Welcome to Debugify v2.1!
Please select an option.
1. Install Debugify
2. Uninstall Debugify
': not a valid identifierad: `option
./debugify.sh: line 46: `elif [ $option == "2" ]
```
installeronly gets further, but still to no avail. stuck on 
```Connecting to 35.227.167.89:80```
Eventually it times out and gives up.

**Comment by iiFir3z** [comment]
Please use the InstallerOnly script as the other one is kinda screwed up.

**Comment by jkrosado** [comment]
> Please use the InstallerOnly script as the other one is kinda screwed up.
> […](#)

wound up doing that but the server it connects to seems to be offline/down
