### ISSUE TITLE
Band Selection not working, showing wrong bands

### ISSUE THREAD

**Issue by XxZ4CK50xX** [iiFir3z/debugify#20]
I have an US Model iPhone X and it's showing Band 33 but not Band 30, no band 66 or band 71. I think it got the bandlist for CN Models or something. I dunno.

I also tried enabling only one band but when i save and go back to settings it doesn't save

iPhone X iOS 13.7 ATT

**Comment by iiFir3z** [comment]
The build used does not have band selection for all phones, as much as I wish it did this feature is only semi supported.
