### ISSUE TITLE
Unable to download frameworks and AppleInternal Stuff

### ISSUE THREAD

**Issue by EnlightDG** [iiFir3z/debugify#6]
Alright so apparently if the debugify.sh script finishes within a few seconds, that means you dont have "curl" installed and that it skipped the download of the frameworks and the AppleInternal components which are both close to 1GB in size each! so if you are having this problem, heres the solution:

1. SSH into your phone using the root account (presuming you haven't already)
2. type `apt install curl -y` (let that install)
3. rerun the script and you should be good to go! (make sure it has permissions by doing: `chmod +x debugify.sh`)

**Comment by iiFir3z** [comment]
The most recent change should have gotten rid of cURL completely in change
for wget as wget handles the job better.

**Comment by EnlightDG** [comment]
well from the script i used which to me hasnt been updated yet, i removed the "clear" commands in the script and it was saying that "curl" was a unknown command so i installed that and it all works

**Comment by iiFir3z** [comment]
cURL shouldn’t exist in the new script but ill double check and patch it
out for 2.0
